name: combine manual aand auto
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: create build
        uses: actions/checkout@v2
      - name: build stage
        run: echo "build the code"
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test stage
        uses: actions/checkout@v2
      - name: test stage
        run: echo "test stage"
  db-stage:
    runs-on: ubuntu-latest
    needs: ['build','tests']
    steps:
      - name: db-launch
        uses: actions/checkout@v2
      - name: db-launch stage
        run: echo "db-launch"
